COLUMNS:
  customer_id: int64
  first_name: object
  last_name: object
  country: object
  age: int64
  gender: object
  income_level: int64
  Winning_percentage: int64
  Days_Since_Last_Bet: int64
  Active_Days: int64
  Total_Number_of_Bets: int64
  Total_Amount_Wagered: int64
  Average_Bet_Amount: int64
  Number_of_Bonuses_Received: int64
  Amount_of_Bonuses_Received: int64
  Revenue_from_Bonuses: int64
  Increase_in_Bets_After_Bonus: int64
  Increase_in_wagering_after_Bonus: int64
  Should_Receive_Bonus: int64
  

TARGET_COLUMNS:
  Should_Receive_Bonus: int64
